name: _Dependabot reviewer

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: write

jobs:
  request-manual-approval:
    name: Request Manual Approve
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Request approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{secrets.GITHUB_TOKEN}}
          approvers: matheus-delre
          minimum-approvals: 1
          issue-title: "Deploying to prod from staging"
          issue-body: "Please approve or deny the deployment to production"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'aprovado'
          additional-denied-words: 'negado'