name: _Template Build

on:
  workflow_call:
    inputs:
      project:
        description: 'The *csproj project path passed from the caller workflow'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget  
      
      - name: Install dependencies
        working-directory: ${{ inputs.project }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ inputs.project }}
        run: dotnet build --configuration Release --no-restore
