name: _Deploy

on:
  workflow_call:
    inputs:
      path:
        description: 'The project path passed from the caller workflow'
        required: true
        type: string
      project:
        description: 'The project passed from the caller workflow'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        description: 'The azure credentials passed from the caller workflow'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no Azure Container Registry (ACR)
        run: az acr login --name acrgalilearn

      - name: Build e Push da imagem Docker para o ACR
        env:
          DOCKERFILE_PATH: ${{ inputs.path }}/${{ inputs.project }}
        run: |
          docker build -f ${{env.DOCKERFILE_PATH}} -t acrgalilearn.azurecr.io/galilearn-api:latest .
          docker push acrgalilearn.azurecr.io/galilearn-api:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform