name: _Terraform Plan

on:
  workflow_call:
    inputs:
      staging-aws:
        description: 'The staging acocunt id aws passed from the caller workflow'
        required: true
        type: string
      production-aws:
        description: 'The production acocunt id aws passed from the caller workflow'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        description: 'The azure credentials passed from the caller workflow'
        required: true

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no Azure Container Registry (ACR)
        run: az acr login --name acrgalilearn

      - name: Build e Push da imagem Docker para o ACR
        env:
          DOCKERFILE_PATH: ${{ inputs.path }}/${{ inputs.project }}/Dockerfile
        run: |
          docker build -f ${{env.DOCKERFILE_PATH}} -t acrgalilearn.azurecr.io/galilearn-api:latest .
          docker push acrgalilearn.azurecr.io/galilearn-api:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no Azure Container Registry (ACR)
        run: az acr login --name acrgalilearn

      - name: Setup - Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: 1.6.6

      - name: "Run - Terraform Init"
        id: init
        run: |
          terraform init
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}

      - name: "Run - Terraform Validate"
        id: validate
        run: |
          terraform validate -no-color
      
      - name: "Run - Terraform Plan"
        id: plan
        run: |
          terraform plan -compact-warnings -no-color -out $BRANCH-out.tfplan
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}

      - name: "Get Plan Result"
        id: getplan
        run: |
          terraform show -no-color $BRANCH-out.tfplan
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}

      - name: "Run - Terraform Comment"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Terraform \`${process.env.BRANCH}\`

            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}
          PLAN: "terraform\n${{ steps.getplan.outputs.stdout }}"