name: _Terraform Plan

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        description: 'The azure credentials passed from the caller workflow'
        required: true

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no Azure Container Registry (ACR)
        run: az acr login --name acrgalilearn

      - name: Setup - Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: 1.6.6

      - name: "Run - Terraform Init"
        id: init
        run: |
          terraform init
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}

      - name: "Run - Terraform Validate"
        id: validate
        run: |
          terraform validate -no-color
      
      - name: "Run - Terraform Plan"
        id: plan
        run: |
          terraform plan -compact-warnings -no-color -out $BRANCH-out.tfplan
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}

      - name: "Get Plan Result"
        id: getplan
        run: |
          terraform show -no-color $BRANCH-out.tfplan
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}

      - name: "Run - Terraform Comment"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Terraform \`${process.env.BRANCH}\`

            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}
          PLAN: "terraform\n${{ steps.getplan.outputs.stdout }}"