name: Workflow Fargate

on:
  workflow_call:
    inputs:
      path:
        description: 'The project path passed from the caller workflow'
        required: true
        type: string
      project:
        description: 'The project passed from the caller workflow'
        required: true
        type: string
      test:
        description: 'The test path passed from the caller workflow'
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        description: 'The Sonar Qube token passed from the caller workflow'
        required: true
      CODECOV_TOKEN:
        description: 'The code cov token passed from the caller workflow'
        required: true
      AZURE_CREDENTIALS:
        description: 'The azure credentials passed from the caller workflow'
        required: true
        
concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened') }}
    uses: ./.github/workflows/_build.yaml
    with:
      project: ${{ inputs.path }}/${{ inputs.project }}
    secrets: inherit  
  test:
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened') }}
    needs: [ build ]
    uses: ./.github/workflows/_test.yaml
    with:
      test: ./${{ inputs.test }}
    secrets: inherit
  sonar_qube:
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened') }}
    needs: [ build ]
    uses: ./.github/workflows/_sonar_qube.yaml
    with:
      project: ${{ inputs.path }}/${{ inputs.project }}
    secrets: inherit

  terraform-plan:
    needs: [ test ]
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened') }}
    uses: ./.github/workflows/_terraform-plan.yaml
    secrets: inherit
